### PR TITLE
Remove deprecated methods for gem version 3.0

### LINKED ISSUE #202: Deprecations for 3.0
## Deprecated in 2.x

Methods and arguments to be removed for version 3.0.

- `lib/appsignal.rb` - `#start_logger`
  - `path_arg` argument is no longer supported. Please remove https://github.com/appsignal/appsignal-ruby/blob/4eed259e122d10df66655098ad0aa8a362f3297d/lib/appsignal.rb#L257-L259
- `lib/appsignal.rb` - `.is_ignored_error?`
  - Deprecated in PR #224 -- remove in 3.0
- `lib/appsignal.rb` - `.is_ignored_action?`
  - Deprecated in PR #224 -- remove in 3.0
- `lib/appsignal/auth_check.rb`
  - `logger` argument - deprecated in #245 
- `lib/appsignal/transaction.rb`
  - ~~`Transaction#store` - deprecated in #33~~ Never actually merged. `Transaction#store` is still used in the mongo_ruby_driver integration.
- `lib/appsignal/config.rb`
  - backwards compatability for older config keys: #359 
- `lib/appsignal/event_formatter.rb`
  - deprecated in #397 
  - https://github.com/appsignal/appsignal-ruby/blob/08437670f72929d2557ac2c29ff51c7b056d51b3/lib/appsignal/event_formatter.rb#L88-L97
- `appsignal notify_of_deploy` - #414 
  - Deprecated in #545 
- `lib/appsignal/integrations/resque.rb` instrumentation - PR #630 
- `lib/appsignal/integrations/resque_active_job.rb` instrumentation - PR #630 

Add more deprecations here (and explicitly deprecate them in the code) once you find them.

## ~~To be deprecated before v3.0~~ (moved to #667)

- `lib/appsignal.rb` - `.monitor_transaction`
  - create a better alternative for this helper
- `lib/appsignal/auth_check.rb`
  - merge `#perform` and `#perform_with_result`
- Capistrano integration's deploy logic.
  - Prefer the `revision` config option instead.

### PR DESCRIPTION
**Pull request by jeffkreeftmeijer**
Closes #202.

This patch removes all methods listed in the "Deprecated in 2.x”-list in #202, except for `Transaction#store`, which was deprecated in #332, but wasn’t ever merged. The methods that were planned to be deprecated have been moved to #667, and will be deprecated before 4.0.

### CODE REVIEW

**Review by matsimitsu — APPROVED** [review]

**Review by tombruijn — APPROVED** [review]
Yay! Cleanup!

Can you rebase to "merge"/combine the fixup commits with the commits they fixup? Fixup commits themselves should not be merged.

**Comment by tombruijn** [comment]
These deprecations may cause some errors people may not expect during an upgrade. So maybe it's an idea to write an upgrade guide for Ruby gem 3.0 as well? Mostly just a list of includes, extends and method calls that need to be removed from an app.

**Comment by jeffkreeftmeijer** [comment]
I’ve added writing an upgrade guide to the integrations board: https://github.com/orgs/appsignal/projects/35, and autosquashed this branch. I’ll wait with merging this until done with #603, so we can build a release.

**Review by thijsc — APPROVED** [review]

**Comment by tombruijn** [comment]
Closing in favor of  #685

**Pull request closed without merging**
