### PR TITLE
Add working_directory_path config option

### PR DESCRIPTION
**Pull request by thijsc**
Add support for working_directory_path.

Docs: https://github.com/appsignal/appsignal-docs/pull/182

### CODE REVIEW

**Comment by tombruijn** [comment]
I think we also immediately want to deprecate the `working_dir_path` config option. So we should print (#419) a deprecation warning to the app's STDOUT when the working_dir_path config option is used.

**Comment by thijsc** [comment]
Added it to `DEPRECATED_CONFIG_KEY_MAPPING`

**Comment by thijsc** [comment]
Oh actually that's wrong. It should print a warning, not set the new config option because that will break.

**Comment by tombruijn** [comment]
Rebased on develop.

**Pull request merged**
