### PR TITLE
Add Rails 7 to CI build

### PR DESCRIPTION
**Pull request by tombruijn**
Test against latest Rails release.

Part of https://github.com/appsignal/appsignal-ruby/issues/786

[skip changeset]

### CODE REVIEW

**Comment by unflxw** [comment]
I took a look at the test failures. I believe the failures in the tests do not mean the underlying functionality is broken; I have not tested the queue functionality, but it seems to be working. All the test failures relate to implementation changes in ActiveJob, and they seem to fall in one of these two buckets:

1) **Events for a job are fired in a different order.** Specifically, the `perform.active_job` event now has a start time prior to that of the `perform_start.active_job` event. Some of our tests check the ordering of these events by start time, expecting `perform_start.active_job` to happen before `perform.active_job`, which does not happen anymore. I could not find a changelog entry for this, which makes me think it _might_ be a bug in ActiveJob? This seems to me like the kind of thing one would mention in a changelog entry if it was an intentional change.

2) **The internal structure of the ActiveJob message is different.** A lot of our tests perform checks against the `transaction_hash` from the last transaction, which contains the ActiveJob message in its sample data params. ActiveJob transforms the given arguments in a way that makes it serializable to JSON without losing certain Ruby-specific information about it. Some of it is already accounted for in our tests: for example, we expect the `_aj_symbol_keys` key to be present in a hash to indicate which of its keys are symbols.  
  In Rails 7, it seems like the arguments to the job are (sometimes?) wrapped in an object containing an `"args"` key. In this object, [the `_aj_ruby2_keywords` key can also be present](https://github.com/rails/rails/commit/fc678575961ada06a72746e438caae201a722205), which, like `_aj_symbol_keys`, _also_ has the symbol keys as its value. But its presence seems to depend on whether [the `ruby2_keywords_hash` flag](https://ruby-doc.org/core-3.0.3/Hash.html#method-c-ruby2_keywords_hash-3F) was present in the original hash. The semantics of that flag are not entirely clear to me, but it seems to be set by a compatibility method [on `Module`](https://ruby-doc.org/core-3.0.3/Module.html#method-i-ruby2_keywords) and [on `Proc`](https://ruby-doc.org/core-3.0.3/Proc.html#method-i-ruby2_keywords), in order to indicate whether the last argument in an `*args` splat represents the keyword arguments, so that it can be treated correctly if those `*args` are, in turn, passed on to another function. The docs say it's "for backwards compatibility with Ruby versions before 2.7", so it must relate to a change in the behaviour of splatted args and keyword arguments in 2.7.
  [Some of our ActiveJob-related tests](https://github.com/appsignal/appsignal-ruby/blob/4940d3b87bdcff595674e5dcd9407f2337d8b107/spec/lib/appsignal/hooks/activejob_spec.rb#L583-L589) already account for this, expecting `_aj_ruby2_keywords` to be used if the Ruby version is higher than 2.7, and `_aj_symbol_keys` to be used otherwise. While this seems to be correct enough for the tests that make use of this helper, I don't think it's correct for the general case: given `*args` of the form `"foo", bar: {baz: 123}`, I believe that `args.last` will be serialised by ActiveJob using `_aj_ruby2_keywords`, in order to indicate that it represents keyword arguments, but `args.last[:baz]` will use `_aj_symbol_keys`. While I'm not sure if I've figured out the semantics of it correctly, [this behaviour can be seen in the test output.](https://appsignal.semaphoreci.com/jobs/1d0c9a91-fd8b-4a38-97fa-99f6aef1c769#L535)

Finally, note that [the JRuby tests for Rails 7 are not running on CI](https://appsignal.semaphoreci.com/jobs/1b09d64d-45a5-44ec-b135-a6f979e8aa92) at the moment, as Rails 7 requires Ruby 2.7.

**Comment by jeffkreeftmeijer** [comment]
Alright, thanks for looking into this. Since the implementation doesn’t seem to be broken, and we haven’t had any reports claiming they are, we can plan time to look into this in the beginning of next year.

**Comment by unflxw** [comment]
There isn't a JRuby version yet that is compatible with Ruby 2.7 or Ruby 3.0, which are the minimum requirements for Rails 7. [There's an ongoing issue for adding support in the next JRuby version.](https://github.com/jruby/jruby/issues/6878)

In light of this, we should not attempt to run the Rails 7 tests on JRuby for the time being. I'll remove that entry in the build matrix.

**Comment by unflxw** [comment]
I think it's fixed now, but someone who actually knows Rails properly should verify that these changes actually address the problem at the right place.

### Fix test failures for Rails 7

This commit fixes the test failures in Rails 7 that were present
due to changes in the ActiveJob internals.

When a job is performed, the `perform_start.active_job` event now
seems to always fire _after_ the `perform.active_job` event.

When a message is serialised by ActiveJob, the arguments and
params passed to the method are now always wrapped in a separate
hash within the `params` key, itself containing `args` and `params`
keys, and subject to the quirks of ActiveJob hash serialisation.

This commit modifies the tests to expect these changes.

**Review by jeffkreeftmeijer — APPROVED** [review]

**Comment by tombruijn** [comment]
For now this looks fine, it's just test fixes.

I do wonder why the test results of the parameters are different from what I see with manual tests. We may need to revisit this, I no longer know why it's like this and I think I wrote it. There may be something wrong with the test data, but what I see on AppSignal.com after testing manually is what I expect.

Given the job is this:
```ruby
class ActiveJobErrorWorker < ActiveJob::Base
  queue_as :default
  sidekiq_options :retry => 3

  def perform(argument = nil, *options, foo: nil)
    raise "Error #{argument}"
  end
end

# Queue job
ActiveJobErrorWorker.perform_later("ActiveJob Error test", { :foo => "bar", "baz" => "bat" }, ["foo", "bar"])
```

I don't see the list of the job action name parts with the arguments wrapped in "args" as we do in the tests. I get the following parameters, which is what I expect:

```json
[
  "ActiveJob Error test",
  {
    "_aj_symbol_keys": [
      "foo"
    ],
    "baz": "bat",
    "foo": "bar"
  },
  [
    "foo",
    "bar"
  ]
]
```

**Pull request merged**
