### PR TITLE
Enable agent diagnostics in diagnose command

### PR DESCRIPTION
**Pull request by thijsc**
This allows us to test the agent in diagnose mode as well rather than just the Ruby gem.

### CODE REVIEW

**Comment by tombruijn** [comment]
See that we don't test if the output from the agent is present in the diagnose output. If I run the test I see it in the test log output rather than part of the diagnose output. Which doesn't make it very readable. Can we capture the agent output?

**Comment by thijsc** [comment]
I don't think that's possible with the way it currently works. You'd have to refactor it quite deeply to make this happen. We'd have to start a separate Ruby process that starts the agent and capture that Ruby processes output.

**Comment by tombruijn** [comment]
@thijsc looks like I can capture the stdout by using `reopen`

```ruby
  def capture_stdout(stdout)
    original_stdout = $stdout.dup
    $stdout.reopen stdout

    yield

    $stdout.reopen original_stdout
  end

capture_stdout(Tempfile.new("foo")) { do_something }
```

The extension continues to write to original_stdout, but if you `reopen` the instance it also applies to the agent.

Going to see if I can easily fix it with this by changing all the `StringIO.new`s (for `out_stream`) to `Tempfile`s and then test the output.

**Comment by tombruijn** [comment]
@thijsc I added test coverage in the latest commit on this PR.

I made all the std stream testing consistent while also switching it from using `StringIO` to `Tempfile`s and `$stdout.reopen new_stream` as you can see in `spec/support/helpers/std_streams_helper.rb`.

The tests fail of course now, because they don't use the latest agent from PR https://github.com/appsignal/appsignal-agent/pull/204 which I also updated to have more a more consistent output with the rest of the diagnose output as you can see below.

Let me know what you think about the changes

```
$ bundle exec appsignal diagnose --environment=production
AppSignal diagnose
================================================================================
Use this information to debug your configuration.
More information is available on the documentation site.
http://docs.appsignal.com/
Send this output to support@appsignal.com if you need help.
================================================================================

AppSignal agent
  Gem version: 2.0.3
  Agent version: f727d42
  Gem install path: /Users/tom/appsignal/agent/integrations/appsignal-ruby
  Extension loaded: yes

Host information
  Architecture: x86_64
  Operating System: darwin16.0.0
  Ruby version: ruby-2.3.0
  root user: no

Agent diagnostics:                                <===== This section is new
  Running agent in diagnose mode                  <===== I added indenting to this
  Valid config present
  Logger initialized successfully
  Lock path is writable
  Agent diagnose finished

Configuration
  Environment: production
  debug: true
  log: stdout
  ignore_errors: []
  ignore_actions: []
  filter_parameters: []
  send_params: true
  endpoint: https://push.staging.lol
  instrument_net_http: true
  instrument_redis: true
  instrument_sequel: true
  skip_session_data: false
  enable_frontend_error_catching: false
  frontend_error_catching_path: /appsignal_error_catcher
  enable_allocation_tracking: true
  enable_gc_instrumentation: true
  running_in_container: false
  enable_host_metrics: true
  enable_minutely_probes: false
  hostname: Akoiwa.local
  ca_file_path: /Users/tom/appsignal/agent/integrations/appsignal-ruby/resources/cacert.pem
  name: Signaltest
  log_path: /Users/tom/appsignal/tests/applications/rails/log
  push_api_key: **snip**
  active: true

Validating API key: Valid

Required paths
  current_path: "/Users/tom/appsignal/tests/applications/rails"
    - Writable?: yes
    - Ownership?: yes (file: tom:501, process: tom:501)
  root_path: "/Users/tom/appsignal/tests/applications/rails"
    - Writable?: yes
    - Ownership?: yes (file: tom:501, process: tom:501)
  log_dir_path: "/Users/tom/appsignal/tests/applications/rails/log"
    - Writable?: yes
    - Ownership?: yes (file: tom:501, process: tom:501)
  log_file_path: "/Users/tom/appsignal/tests/applications/rails/log/appsignal.log"
    - Writable?: yes
    - Ownership?: yes (file: tom:501, process: tom:501)

Extension install log
  Path: "/Users/tom/appsignal/agent/integrations/appsignal-ruby/ext/install.log"
  Contents:
**Snip**

Makefile install log
  Path: "/Users/tom/appsignal/agent/integrations/appsignal-ruby/ext/mkmf.log"
  File not found.
```

**Pull request merged**
