### PR TITLE
Support for Ruby 2.4.0

### LINKED ISSUE #225: Ruby 2.4 support
Some change were made in fixnum and bignum: https://www.ruby-lang.org/en/news/2016/12/25/ruby-2-4-0-released/

### PR DESCRIPTION
**Pull request by thijsc**
Work in progress. The way integers work has changed: http://www.a-k-r.org/pub/2016-09-08-rubykaigi-unified-integer.pdf

We're researching whether we need to make changes to support this at the moment.

Fixes #225

### CODE REVIEW

**Comment by tombruijn** [comment]
Can't seem to figure out how to get the extension to handle BigNums/Int64/Int64+. I don't know if it is at all possible while keeping the original data type (so no `to_s`).
Pushed my latest attempt.

Would be great if someone else can take a look.

Related issue/same problem: https://github.com/appsignal/appsignal-elixir/issues/88

**Comment by tombruijn** [comment]
PR is ready for review with one remark. I added the Rails builds for version 4.0, 4.1 and 4.2 (and resque using Rails 4.2) on Ruby 2.4 to allowed failures. Something is causing a segfault there. I think it's a Rails dependency, but couldn't narrow it down.
Happens on Ruby 2.4 on the `develop` branch as well.

**Comment by tombruijn** [comment]
@thijsc I can't assign you as reviewer, because you originally created the PR, but can you review as well?

**Comment by thijsc** [comment]
Looks good, thanks!

**Pull request merged**
