### PR TITLE
Support setting a specific configuration file

### PR DESCRIPTION
**Pull request by thijsc**
Add an extra argument to the config initializer so one can pick a specific configuration file.

### CODE REVIEW

**Comment by tombruijn** [comment]
Have we had a request for this, or what's the reason for the change?

**Comment by thijsc** [comment]
Was requested [here](https://app.intercom.com/a/apps/yzor8gyw/inbox/inbox/14888/conversations/16410700001565).

**Comment by scottdavis** [comment]
Where are we at with getting this added?

**Comment by thijsc** [comment]
The change is already made, you could try it using this branch. I expect this one will end up in the next release.

**Comment by tombruijn** [comment]
I'll try and get it out Monday. I've been busy with the 2.11 release

**Comment by tombruijn** [comment]
@scottdavis I've just published Ruby gem 2.10.11 with this change 🎉

**Comment by scottdavis** [comment]
Thanks!! @tombruijn @thijsc

**Pull request merged**
