### PR TITLE
DNS config is an array

### PR DESCRIPTION
**Pull request by thijsc**
The DNS servers config option was incorrectly in the string keys list, it is actually an array.

### CODE REVIEW

**Review by tombruijn — APPROVED** [review]
This should have been okay, because it's never used by the Ruby integration and passed along as a String to the extension, which still sends it in the same format even with this change because it joins it with `join(",")`. It's just the correct type in the Ruby integration now.

**Comment by tombruijn** [comment]
@thijsc was this a bug fix for something? Because while this change is more correct, this doesn't change how the config is send to the extension.

**Comment by thijsc** [comment]
This was actually broken when setting it as an env var. It tried to join a string.

**Comment by tombruijn** [comment]
@thijsc ok, shall we then release it as a patch release?

**Comment by tombruijn** [comment]
Released in 3.0.1

**Pull request merged**
