### PR TITLE
🚀 Que integration

### PR DESCRIPTION
**Pull request by tmiller**
### Description

Add instrumentation and exception reporting for Que. 
* Instrumentation is added by using meta programming around the `Que::Job#_run`.
* Error reporting is implemented by passing an error handler to `Que#error_handler` since Que already handles exceptions.

### CODE REVIEW

**Comment by tmiller** [comment]
I don't believe the exception reporting is working just yet, so please hold of on pulling this.

**Comment by tmiller** [comment]
It seems to be working. I was running into problems because I was running the job synchronously, which doesn't not call `_run` but instead calls `run` directly so you can debug exceptions in the rails server or console.

**Comment by tombruijn** [comment]
Hi @tmiller ,

Thanks for the PR!
Looks like it's using some outdated test suite setup. We're slowly trying to rewrite everything in issue #252 . I would like to rewrite the specs to use that before merging.

Also, do you have an example app you can share with us? Something we can add to this repo: https://github.com/appsignal/appsignal-examples

**Comment by tmiller** [comment]
@tombruijn I've made the changes, can you please review the changes to the tests? I am also working on setting up an example application as requested.

**Comment by tombruijn** [comment]
@tmiller That's great! Thanks for already updating the specs to use `Appsignal::Transaction#to_h`!
I'll review it and let you know if any further changes are needed.

**Comment by tmiller** [comment]
Here you go https://github.com/ProctorU/appsignal-examples/tree/rails-5+que

**Comment by tombruijn** [comment]
@tmiller That's amazing! I was just starting to set up an example app 😁 

I'll try it out, test the integration you wrote and merge it into the examples repo

Let me know if you still have time to fix the comments I had earlier. If you don't have time, I'll push the fixes to this PR. After that I'll submit it to review for the rest of the team.

**Comment by tmiller** [comment]
Thanks I have time They will be done in a few minutes :)

**Comment by tombruijn** [comment]
@tmiller upon reviewing it against the example I noticed that ActiveJob is not tested in the test suite? I was trying something myself in this branch: https://github.com/appsignal/appsignal-ruby/tree/aj-que-integration
but so far have had no luck with it. Do you have any experience with testing it directly like so?

If this doesn't work we may have to revise the tests to only test the plugin itself without being included in the Que::Job class. I wouldn't want to have to add the postgresql dependency either.

**Comment by tmiller** [comment]
We don't use ActiveJob. I think that was left over from the code before I picked it up. I haven't tried testing it, and I won't be able to work on adding tests and correct support for ActiveJob until Friday. I'm ok with removing the ActiveJob parts if you are?

**Comment by tombruijn** [comment]
@tmiller we've discussed it here and we're okay with merging it without the ActiveJob support. I'd rather we take the ActiveJob logic out entirely and have another look at it in issue #330

**Comment by tmiller** [comment]
Thanks! I've removed the code, anything else you need?

**Comment by tombruijn** [comment]
@tmiller no, I think that's it! I've requested reviews from the team. Let's see if anyone else has any comments :)

**Comment by tombruijn** [comment]
Thanks again @tmiller for the PR!
We'll try to release this in the upcoming 2.4.1 release. Which we hope will be sometime this week. It's waiting for PR #366 to be merged and tested.

**Comment by tombruijn** [comment]
@tmiller this is now released in AppSignal gem v2.4.1 🎉

**Comment by tmiller** [comment]
Thanks, for all the help!

**Pull request merged**
