### PR TITLE
Add support for NGINX metrics

### PR DESCRIPTION
**Pull request by unflxw**
Add `enable_nginx_metrics` config option. Update the diagnose tests submodule to expect the option.

Update the agent version to support NGINX metrics.

### CODE REVIEW

**Comment by unflxw** [comment]
@thijsc This should be ready to throw at staging. Ping me tomorrow and we can go through it.

**Comment by tombruijn** [comment]
@unflxw it's related to a change we made in the protocol. I've pushed a fix.

**Review by tombruijn — APPROVED** [review]
I pushed some fixes. Should be good now.

**Review by thijsc — APPROVED** [review]

**Comment by unflxw** [comment]
Thanks for the fixes @tombruijn!

**Pull request merged**
