### PR TITLE
SidekiqPlugin: get env from Sidekiq::Job

### PR DESCRIPTION
**Pull request by rmachielse**
This pr slightly changes the way information about sidekiq jobs is retrieved.
Instead of using the job's data hash, the job object is instantiated, allowing the use of already implemented logic.

In practice, this leads to more readable action names and param hashes.
The action name used to always be `Sidekiq::Extensions::DelayedClass#perform` when using the form of `Model.delay.method`. That will now be `Model#method`. Also `ActionMailer` jobs will now be reported with their actual class name instead of `ActionMailer::DeliveryJob#perform`.

In addition, the params are now reported as a proper array, instead of the raw `ARGV` array.

### CODE REVIEW

**Comment by jeffkreeftmeijer** [comment]
Thanks for diving into this, @rmachielse!

For the rest; I talked about this briefly with Richard [on Intercom](https://app.intercom.io/a/apps/yzor8gyw/respond/inbox/540654/conversations/11721431210) (private   link).

**Comment by rmachielse** [comment]
@jeffkreeftmeijer no problem, let me know if I can help!

**Comment by tombruijn** [comment]
We're going to discuss this next week with @jeffkreeftmeijer @matsimitsu and myself, and let you know how we're going to fix and merge this.

**Comment by rmachielse** [comment]
@tombruijn awesome, thanks!

**Comment by thijsc** [comment]
Thanks for you contribution! We're continuing this in a slightly different form in #348

**Comment by rmachielse** [comment]
@thijsc thanks a lot for that!

**Pull request closed without merging**
