### PR TITLE
Remove deprecated commands, do not use Gem::Deprecate 

### PR DESCRIPTION
**Pull request by simi**
- and make gem rubygems master compatible again

:information_source: recent change in rubygems changes signature of deprecate method.

https://github.com/rubygems/rubygems/commit/3a14635cf50e9d702eeb243a7a83535748fbaee0#diff-903104a71cfc2ce2b3565670df8ad2a2L91

```
        10: from /home/retro/.gem/ruby/2.5.7/gems/bundler-1.17.3/lib/bundler.rb:114:in `require'                                                                                              
         9: from /home/retro/.gem/ruby/2.5.7/gems/bundler-1.17.3/lib/bundler/runtime.rb:65:in `require'                                                                                       
         8: from /home/retro/.gem/ruby/2.5.7/gems/bundler-1.17.3/lib/bundler/runtime.rb:65:in `each'                                                                                          
         7: from /home/retro/.gem/ruby/2.5.7/gems/bundler-1.17.3/lib/bundler/runtime.rb:76:in `block in require'                                                                              
         6: from /home/retro/.gem/ruby/2.5.7/gems/bundler-1.17.3/lib/bundler/runtime.rb:76:in `each'                                                                                          
         5: from /home/retro/.gem/ruby/2.5.7/gems/bundler-1.17.3/lib/bundler/runtime.rb:81:in `block (2 levels) in require'                                                                   
         4: from /home/retro/.gem/ruby/2.5.7/gems/bundler-1.17.3/lib/bundler/runtime.rb:81:in `require'                                                                                       
         3: from /home/retro/.gem/ruby/2.5.7/gems/appsignal-2.9.16/lib/appsignal.rb:16:in `<top (required)>'                                                                                  
         2: from /home/retro/.gem/ruby/2.5.7/gems/appsignal-2.9.16/lib/appsignal.rb:17:in `<module:Appsignal>'                                                                                
         1: from /home/retro/.gem/ruby/2.5.7/gems/appsignal-2.9.16/lib/appsignal.rb:286:in `singleton class'                                                                                  
/home/retro/.rubies/ruby-2.5.7/lib/ruby/site_ruby/2.5.0/rubygems/deprecate.rb:54:in `deprecate': wrong number of arguments (given 4, expected 1..2) (ArgumentError)
```

Those methods are marked as deprecated for long time. The easiest fix is to remove them and do not use `Gem::Deprecate` at all.

### CODE REVIEW

**Comment by tombruijn** [comment]
Hi @simi ,

Thanks for the PR! I don't think we want to remove the methods yet. The deprecate methods needed _any date_ value as the arguments. The dates themselves don't mean much. We have planned to remove them in version 3 of this gem, see #202.

We can update the method call, or implement our own deprecation logic, or do I understand from the linked rubygems issue's discussion (https://github.com/rubygems/rubygems/pull/3414) that the change may be reverted ?

**Comment by simi** [comment]
Yes, that change would be probably reverted. Anyway there's already https://github.com/appsignal/appsignal-ruby/blob/490bc24973a8ca94004078580d9a32a01c74ad9c/lib/appsignal/utils/deprecation_message.rb. Any reason to not use it for those methods as well?

**Comment by tombruijn** [comment]
Hi @simi, yes.. that looks like it would be better to use then if we're using `Gem::Deprecate` in a way that wasn't intended. Let's do that then. (I honestly forgot we had that module 😅 )

**Comment by simi** [comment]
It was reverted already at https://github.com/rubygems/rubygems/pull/3530. Since it is not possible to remove those deprecated methods, this PR doesn't make sense anymore. You need to decide if using `Gem::Deprecate` is safe enough for you. I think there's no guarantee from rubygems side it would not change in the future.

**Comment by tombruijn** [comment]
Thanks for the nudge @simi. I've created issue #600 for it :)

**Pull request closed without merging**
