### PR TITLE
Add MRI probe

### PR DESCRIPTION
**Pull request by thijsc**
Add minutely probe that collects metrics for `:class_serial` and  `:global_constant_state` from `RubyVM`.

### CODE REVIEW

**Comment by tombruijn** [comment]
@thijsc I fixed the diagnose tests on the main branch.

**Comment by thijsc** [comment]
Thanks! I'll rebase.

**Review by tombruijn — APPROVED** [review]
Looks good 👍 
This probably also needs a PR on the public_config repo for a magic dashboard?

**Comment by thijsc** [comment]
> This probably also needs a PR on the public_config repo for a magic dashboard?

Yes. I'll be working on a blog post and adding it there. We can release this regardless. It's fine if it's already in a release before we announce it.

**Review by luismiramirez — APPROVED** [review]

**Pull request merged**
