### PR TITLE
Use base namespace to check Redis version

### LINKED ISSUE #542: [v2.9.8] uninitialized constant Appsignal::Redis::VERSION
## Describe the bug

I've got this error at boot in my app

```
/app/vendor/bundle/ruby/2.6.0/gems/appsignal-2.9.8/lib/appsignal/hooks/sidekiq.rb:29:in `dependencies_present?': uninitialized constant Appsignal::Redis::VERSION (NameError)
2019-06-13 14:52:00.897273180 +0200 CEST [web-1] #<Thread:0x00007f98638da5d8@/app/vendor/bundle/ruby/2.6.0/gems/appsignal-2.9.8/lib/appsignal/minutely.rb:138 run> terminated with exception (report_on_exception is true):
/app/vendor/bundle/ruby/2.6.0/gems/appsignal-2.9.8/lib/appsignal/minutely.rb:197:in `dependencies_present?'
/app/vendor/bundle/ruby/2.6.0/gems/appsignal-2.9.8/lib/appsignal/minutely.rb:186:in `block in initialize_probes'
/app/vendor/bundle/ruby/2.6.0/gems/appsignal-2.9.8/lib/appsignal/minutely.rb:116:in `each'
/app/vendor/bundle/ruby/2.6.0/gems/appsignal-2.9.8/lib/appsignal/minutely.rb:116:in `each'
/app/vendor/bundle/ruby/2.6.0/gems/appsignal-2.9.8/lib/appsignal/minutely.rb:178:in `initialize_probes'
/app/vendor/bundle/ruby/2.6.0/gems/appsignal-2.9.8/lib/appsignal/minutely.rb:140:in `block in start'
```

- Using AppSignal for Ruby gem version 2.9.8
- In my app using redis 4.1.2

It seems to be a scope error accessing `Redis::VERSION` instead `::Redis::VERSION` maybe ?

### PR DESCRIPTION
**Pull request by bobmaerten**
Fixes #542

### CODE REVIEW

**Comment by tombruijn** [comment]
Hi @bobmaerten ,

Thanks for the PR!
Did you confirm locally your PR fixed the issue?

How can we reproduce this? Set up a simple Redis only Ruby app? or do you have an example app?

**Comment by bobmaerten** [comment]
Nope did'nt test it locally, sorry. I'll try to assemble a sample rails app to test this.

**Comment by bobmaerten** [comment]
I did reproduce the error by running locally my app with `bundle exec rails server`

**Comment by bobmaerten** [comment]
After `bundle open appsignal` fixing bug like this PR, `spring stop && bundle exec rails server`

Error does not trigger.

```
=> Booting Puma
=> Rails 5.2.3 application starting in development
=> Run `rails server -h` for more startup options
[76714] Puma starting in cluster mode...
[76714] * Version 3.12.1 (ruby 2.6.3-p62), codename: Llamas in Pajamas
[76714] * Min threads: 5, max threads: 5
[76714] * Environment: development
[76714] * Process workers: 2
[76714] * Preloading application
[76714] * Listening on tcp://localhost:3000
[76714] Use Ctrl-C to stop
[76714] - Worker 0 (pid: 77125) booted, phase: 0
[76714] - Worker 1 (pid: 77126) booted, phase: 0
C[76714] - Gracefully shutting down workers...
[76714] === puma shutdown: 2019-06-13 16:11:59 +0200 ===
[76714] - Goodbye!
Exiting
```

**Comment by tombruijn** [comment]
That's odd. You do have Redis at all in your bundle?

I think we also need to check if `Redis` is present and loaded at all, but we can do that in another PR.
Redis should be present because Sidekiq is present and depends on it, but Ruby should also look up the chain for the `Redis` constant. 🤔

**Comment by bobmaerten** [comment]
I don't know thy `Redis::VERSION` is resolved as `Appsignal::Redis::VERSION`.
I'll try to setup a test app to be sure.

**Pull request merged**
