### PR TITLE
Add Ruby 3.0 to CI builds

### PR DESCRIPTION
**Pull request by thijsc**
Add Ruby 3.0 support. Removes some older Ruby and Rails versions, adds Rails 6.1. Pull request on develop so this can be part of the upcoming 3.0 gem release.

### CODE REVIEW

**Comment by thijsc** [comment]
Extension installation is failing on `3.0.0-preview1`, but working on my local machine with 3.0.0. Asking Semaphore when 3.0.0 will be available.

**Comment by thijsc** [comment]
Running on Ruby 3.0.0 now, you can update ruby build.

**Comment by thijsc** [comment]
Made a change in the extension download code, let's see if the build is green now.

**Comment by thijsc** [comment]
Status update: All CI builds are now green, looks like everything is working.

**Review by jeffkreeftmeijer — APPROVED** [review]

**Comment by tombruijn** [comment]
Are we dropping support for the older Rubies and Rails versions?

**Comment by thijsc** [comment]
> Are we dropping support for the older Rubies and Rails versions?

This is planned for the upcoming 3.0 gem version already. Would make sense to synchronize this.

**Comment by tombruijn** [comment]
From what I remember that was only Ruby 1.9, not everything below 2.4.

**Comment by thijsc** [comment]
> From what I remember that was only Ruby 1.9 that we are removing support for, not everything below 2.5 and Rails.

I was looking at what's still supported, even 2.5 is not anymore. So that seemed like a good cutoff point for the next major release. I don't have a very strong opinion on this, it's just that some builds fail on 2.4 and below. We'd need a more elaborate YAML loading backport.

**Comment by tombruijn** [comment]
From what I can remember from [this discussion](https://github.com/appsignal/handbook/issues/155#issuecomment-604330965) we talked about dropping 1.9 only (my last comment was posted 1 minute after your (Thijs) so I couldn't really have read your). Any further version support policy was going to be based on the environment metadata, I think?
But if we decide to drop all Ruby versions before 2.6 we need to document that support policy. A continuously updated support policy: when the Ruby team drops support, we drop support. Not sure if that's what we want?

**Comment by spickermann** [comment]
For us, the AppSignal gem is the only blocker for migrating our applications to Ruby 3.0. Is there a timeline when this branch will be deployed? And – if the discussion about removing Ruby < 2.6 support from AppSignal takes longer – is it an option to enable Ruby 3.0 independently from unsupporting older Ruby versions?

**Comment by tombruijn** [comment]
I'm taking a better look at this today to see if I can fix the individual issues (like #680, #679) and apply the Ruby 3.0 support on `main` so we can do a patch release.

**Comment by tombruijn** [comment]
PR with backport in #681
Once that's merged we should merge main into develop after #676 is merged, which drops Ruby 1.9 support again.
Closing this PR.

**Pull request closed without merging**
