### PR TITLE
Add Webmachine integration

### PR DESCRIPTION
**Pull request by matsimitsu**
Try it out:

```
gem 'appsignal', :git => 'https://github.com/appsignal/appsignal-ruby.git', :branch => 'webmachine_develop'
```

Documentation: http://docs.appsignal.com/getting-started/supported-frameworks.html#webmachine

### CODE REVIEW

**Comment by thijsc** [comment]
@matsimitsu Could you rebase this branch on `master`? That will fix the build.

**Comment by matsimitsu** [comment]
Absolutely!

**Comment by tombruijn** [comment]
Looks ok for as far as I understand webmachine 👍 
We don't have a test app for this, do we?

**Comment by matsimitsu** [comment]
I have, let me see if I can pull it into the `test-setups` repo

**Comment by tombruijn** [comment]
👍

**Comment by matsimitsu** [comment]
Done! https://github.com/appsignal/test-setups

**Comment by tombruijn** [comment]
@matsimitsu ready to merge so we can release 1.3 or do you want more reviews?

**Comment by matsimitsu** [comment]
I'm good! merge away :)

**Pull request merged**
