### PR TITLE
Support queueing time metrics for ResqueActiveJob

### PR DESCRIPTION
**Pull request by andjosh**
ActiveJob now supports reporting on the time each job was enqueued, so we can report this as the queue_start in our transaction.

Ref: https://api.rubyonrails.org/classes/ActiveJob/Core.html

This current implementation also supports previous Rails versions by checking presence of the enqueued_at attribute.

### CODE REVIEW

**Comment by matsimitsu** [comment]
Hi @andjosh! Thanks for the pull! Would you be able to rebase on master, it should fix the errors that prevent the CI from running.

**Comment by tombruijn** [comment]
A rebase will fix the build, but we will also need to add some specs for the queue time registration change. Would you be up for that @andjosh, otherwise we can have a look next week.

**Comment by andjosh** [comment]
@matsimitsu I've rebased and the CI does seem to be good now.

@tombruijn I'm having issues setting up the requisite environment to run the spec suite, so I think I'll leave that for you all unless you have specific steps I could take to run the specs for `resque_active_job_spec.rb` (sorry!).

**Comment by tombruijn** [comment]
Hi @andjosh, that's ok, I'll pick it up.
For the future, we have a [section in the README](https://github.com/appsignal/appsignal-ruby#testing-with-other-gems) that describes how to run the test suite against a specific gem. In this case I'm going to test it against a Rails gemfile, so that it includes ActiveJob.

**Comment by tombruijn** [comment]
@andjosh I've created a new PR for this addition. The original code needed a nil check to make sure it doesn't try to parse `nil` as Time. I've also had to do some refactoring for the resque active job test file. Closing this in favor of #616 

Can you try out that PR and let me know if it works?

**Comment by andjosh** [comment]
Looks good to me! Thanks @tombruijn!

**Comment by tombruijn** [comment]
@andjosh thanks for letting me know! We'll release it as a patch release on Monday.

**Comment by tombruijn** [comment]
@andjosh I've released the fix in #616 in version 2.10.9 of the gem.

**Pull request closed without merging**
