### PR TITLE
Adds possibility to override user for deploy

### PR DESCRIPTION
**Pull request by kjeldahl**

### CODE REVIEW

**Comment by kjeldahl** [comment]
We are currently using vagrant for my development and it is not possible to see who has deployed as all are deploying as the user vagrant.

**Comment by tombruijn** [comment]
Hi @kjeldahl and thanks for the PR!
Interesting scenario you have there 🤔 

We're going to review this internally and see if this is the way we want to solve this as well. Will keep you posted!

**Comment by tombruijn** [comment]
Things to discuss internally

- Do we agree with the env var name? Maybe something like `APPSIGNAL_DEPLOY_USER`?
- Add Capistrano 3 support

**Comment by matsimitsu** [comment]
+1 for `APPSIGNAL_DEPLOY_USER`:)

**Comment by tombruijn** [comment]
@thijsc @jeffkreeftmeijer do you agree with the `APPSIGNAL_DEPLOY_USER` env var name?

**Comment by tombruijn** [comment]
Continued in #355. @kjeldahl let me know if the change in that PR works for your scenario or not

**Comment by kjeldahl** [comment]
The capistrano config option looks good and as you write it is possible to populate it in a lot of different ways, instead of relying on an environment variable only.
Thanks for the great work.

**Comment by tombruijn** [comment]
No problem 😃 
We'll try to release this in a point release soon, probably 2.3.8

**Pull request closed without merging**
