### PR TITLE
Improve Rails/Rack request instrumentation

### PR DESCRIPTION
**Pull request by tombruijn**
## Improve Rails/Rack request instrumentation

Rework the Rails instrumentation to use the Rack::Events module to start and complete the transaction at the very start and end of the request. A new middleware is added at the very top of the middleware stack to start and complete the transaction.

This allows us to instrument more of the request's duration, as we're now at the very start and end of the request handling. We will now report the time the request has spend handling any other middleware. This will be visible with a new `process_request.rack` event.

To make sure we always close the transaction, listen for the `on_finish` event, but also register a last resort "after_reply" callback. This callback is supported by web servers like Puma and Unicorn. If it's called when a transaction is active, it will close it, preventing transactions to span multiple requests. If no transaction is active, it will do nothing.

Moving forward, I'd like to update our Rack, Sinatra, Padrino, Grape, etc. instrumentations to use this EventHandler middleware too, which will be a bit more work, because some require users to manually add middleware. When they all use the same EventHandler, we have one place to start and complete transactions, and issues like https://github.com/appsignal/appsignal-ruby/issues/289 cannot happen again in the future.

Previously, our only Rails instrumentation was positioned after the DebugExceptions middleware, just in time to catch any errors before the Rails error middleware showed a nice error/debug page. This wouldn't show the complete picture in request duration.

The original Rails instrumentation middleware will remain to report errors and Rails specific metadata. This cannot be part of the EventHandler, without overloading it with responsibilities, and for Rails error reporting we need to be right after the DebugExceptions middleware before errors are no longer bubbled up in the stack.

Instead of the transaction ID being the request ID, set a new `request_id` tag to not break existing behavior.

Part of https://github.com/appsignal/appsignal-ruby/issues/329

## Ignore requests without a Rails controller

Don't set the action from the AppSignal EventHandler. This `request.path` is not normalized and we would report too many unique actions. This means the EventHandler can't be used on its own without calling `Appsignal.set_action`.

We do this so that for Rails (the only instrumentation that uses the EventHandler right now), will not report any samples for requests for assets. Those asset requests will not have a controller, the RailsInstrumentation middleware will not report an action name, and the extension will drop the transaction as no action name is set.

## Check Rails filtered_parameters method presence

Replicate the same behavior as in `Transaction#request_params` and check if the method exists before calling it.

## Set the Rails request ID tag in the ensure block

Move as much as possible to the ensure block so it's done after the request. The only exception being params as it would overwrite any custom set params calling `Transaction#params=`.

### CODE REVIEW

**Review by luismiramirez — APPROVED** [review]

**Comment by unflxw** [comment]
Tried this out on our test setups (used `rails7-sequel`) and found the following issues:

### Non-routed requests become performance events

Requests for endpoints other than routes, such as those for static assets and non-existent URLs, become performance events. This adds a lot of noise to the performance events panels, as the URL is unique for each asset. For most HTTP frameworks (including Rails before this change) we remove requests that aren't handled through the routing system.

Screenshot 2024-06-05 at 13 03 40

### Missing event color for `action_dispatch`

We now instrument an event representing how `action_dispatch` routes the request. We should assign it a color, like we do for other event groups.

**Comment by tombruijn** [comment]
> ### Non-routed requests become performance events
> 
> Requests for endpoints other than routes, such as those for static assets and non-existent URLs, become performance events. This adds a lot of noise to the performance events panels, as the URL is unique for each asset. For most HTTP frameworks (including Rails before this change) we remove requests that aren't handled through the routing system.

This only happens in development. On production, if the app is configured it properly, it will serve the precompiled assets statically, and not through Rails. For the case in development, we could ask the router if the route is known and discard the transaction if it's not known.

This is the best I've found.

```ruby
def call_with_appsignal_monitoring(env)
  request = ActionDispatch::Request.new(env)
  transaction = env.fetch(
    Appsignal::Rack::APPSIGNAL_TRANSACTION,
    Appsignal::Transaction::NilTransaction.new
  )

  unless handled_request?(request)
    transaction.discard!
    return @app.call(env)
  end

  # ...
end

def handled_request?(request)
  routes = request.env["action_dispatch.routes"]
  routes&.recognize_path(request.path, :method => request.method)
rescue ActionController::RoutingError
  false
end
```

**Comment by unflxw** [comment]
That seems good to me. Definitely let's not do a list of hardcoded paths 😅

**Comment by tombruijn** [comment]
> ### Missing event color for `action_dispatch`
> 
> We now instrument an event representing how `action_dispatch` routes the request. We should assign it a color, like we do for other event groups.

We can update this once approved and merged.

**Review by unflxw — APPROVED** [review]

**Comment by tombruijn** [comment]
Tested it with a nested Sinatra app:

```ruby
# config/routes.rb
require "sidekiq/web"
require 'sinatra/base'

class SinatraApp < Sinatra::Base
  get '/' do
    'Hello from Sinatra!'
  end

  get '/example' do
    'This is an example route in Sinatra.'
  end
end

Rails.application.routes.draw do
  mount SinatraApp, at: "/sinatra"

  # ...
end
```

This discards the request too, because it can't recognize the sinatra mount as a route 🤔 So this is not something we want to merge in its current state.

**Comment by unflxw** [comment]
@tombruijn Interestingly, I think the way that `appsignal.ignore_trace` works would be ideal for this. Set it to `true` in Rack, which is the outer scope, and then override it to `false` in spans for inner framework-specific middlewares that handle routing. (But of course, we'd need to implement that for the transaction API)

**Comment by tombruijn** [comment]
> @tombruijn Interestingly, I think the way that `appsignal.ignore_trace` works would be ideal for this. Set it to `true` in Rack, which is the outer scope, and then override it to `false` in spans from inner framework-specific middlewares that handle routing. (But of course, we'd need to implement that for the transaction API)

I hope we can do without that so that the event handler can be used on its own as a replacement for the rack middleware so you only have to add one.

**Comment by unflxw** [comment]
@tombruijn But in practice, if you're only using Rack (meaning, in practice, that you're using something else that we don't support to handle routing) you'd also want to tell us in some way what routes are or aren't meaningful, right? It could be similar to [how we document WSGI/ASGI support in Python](https://docs.appsignal.com/python/instrumentations/wsgi.html#grouping-routes).

**Comment by tombruijn** [comment]
As discussed, I'm reverting the implementation to the original behavior of the Rack EventHandler not setting an action name, which is good because we can't normalize the URL anyway. (This requires apps using the EventHandler to call `Appsignal.set_action` manually.)

The Rails middleware will only set an action name if there's a controller found. If not, and an asset request is instrumented, no action name is set, and the transaction is dropped by the extension.

**Comment by tombruijn** [comment]
Without further comments, I will merge this next week. To be released some time after. Let's keep an out in support to see if any weirdness gets reported like last time we changed something on the Rack / Rails instrumentation.

**Review by unflxw — APPROVED** [review]

**Pull request merged**
