### PR TITLE
Use doubles in custom metrics

### PR DESCRIPTION
**Pull request by thijsc**
The extension now uses doubles for all values, update the type mapping.

### CODE REVIEW

**Comment by tombruijn** [comment]
@thijsc what's the status of this? When do we want to release this?

**Comment by thijsc** [comment]
We need an agent build to get a green CI build here. This can go out as part of the next release.

**Comment by matsimitsu** [comment]
Nothing has been done about the Elixir integration right? Maybe me/Tom can pick that up after we decide on a release order, so we can close all these waiting pulls :)

**Comment by thijsc** [comment]
Don't think so? @jeffkreeftmeijer did you plan this?

**Pull request merged**
